<style>
    .daterange-action {box-sizing: border-box;}

    /* Style the input container */
    .daterange-action .input-container {
        display: flex;
        width: 400px;
        margin-top: 8px;
        padding-left: 40px;
    }

    /* Style the form icons */
    .daterange-action .icon {
        padding: 5px;
        background: #41362f;
        color: white;
        min-width: 30px;
        text-align: center;
        border-radius: 5px 0 0 5px;
    }

    /* Style the input fields */
    .daterange-action .input-field {
        width: 100%;
        padding: 10px;
        outline: none;
    }

    .daterange-action .input-field:focus {
        border: 2px solid dodgerblue;
    }
</style>

<div class="daterange-action">

    <div class="input-container">
        <i class="fa fa-calendar icon"></i>
        <input type="text" name="daterange" value=""/>
    </div>

    <script>
        require(['jquery', 'moment', 'date-range-picker-lib'], function ($, moment) {
            $(document).ready(function () {
                var inputField =  $('input[name="daterange"]');
                var params = (new URL(document.location)).searchParams;
                var options = {
                    autoUpdateInput: false,
                    showDropdowns: true,
                    showWeekNumbers: true,
                    alwaysShowCalendars: true,
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    locale: {
                        format: 'YYYY-MM-DD',
                        cancelLabel: 'Clear'
                    }
                }
                var inputVal = '';
                if (params.get('startDate')) {
                    options.startDate = params.get('startDate');
                    inputVal = params.get('startDate');
                }
                if (params.get('endDate')) {
                    options.endDate = params.get('endDate');
                    inputVal += ' - ' + params.get('endDate');
                }
                inputField.val(inputVal);
                inputField.daterangepicker(options,
                    function(start, end, label) {
                        var params = (new URL(document.location)).searchParams;
                        if (!start) {
                            params.delete('startDate');
                        } else {
                            params.set('startDate', start.format('YYYY-MM-DD'));
                        }
                        if (!end) {
                            params.delete('endDate');
                        } else {
                            params.set('endDate', end.format('YYYY-MM-DD'));
                        }
                        inputField.val(start.format('YYYY-MM-DD') + ' - ' + end.format('YYYY-MM-DD'));
                        console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
                        var search = params.toString();
                        if (search) {
                            search = '?' + search;
                        }
                        window.location.href = window.location.protocol + "//" + window.location.host + window.location.pathname + search;
                    });
                inputField.on('cancel.daterangepicker', function(ev, picker) {
                    var params = (new URL(document.location)).searchParams;
                    params.delete('startDate');
                    params.delete('endDate');
                    var search = params.toString();
                    if (search) {
                        search = '?' + search;
                    }
                    window.location.href = window.location.protocol + "//" + window.location.host + window.location.pathname + search;
                    $(this).val('');
                });
            });
        });
    </script>
</div>
